#!/usr/bin/env bash
# Script that displays text indefinitely and display message on SIGTERM
b=0
while [ $b -le 3 ]
do
	trap "echo I am invincible!!!" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
