#!/usr/bin/env bash
# Script that displays text indefinitely and display message on SIGTERM
counter=1
trap func SIGTERM
function func() {
	echo "I am invincible!!!"
}
while [ $counter -eq 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
